# SPDX-FileCopyrightText: 2025 Battelle Memorial Institute
# SPDX-License-Identifier: BSD-2-Clause
schema = 3

[operators.gates]

# Supported qubit gates
PauliX = { properties = ["controllable", "invertible"] }
PauliY = { properties = ["controllable", "invertible"] }
PauliZ = { properties = ["controllable", "invertible"] }
Hadamard = { properties = ["controllable", "invertible"] }
S = { properties = ["controllable", "invertible"] }
T = { properties = ["controllable", "invertible"] }
RX = { properties = ["controllable", "invertible", "differentiable"] }
RY = { properties = ["controllable", "invertible", "differentiable"] }
RZ = { properties = ["controllable", "invertible", "differentiable"] }
CRX = { properties = ["invertible", "differentiable"] }
CRY = { properties = ["invertible", "differentiable"] }
CRZ = { properties = ["invertible", "differentiable"] }
CNOT = { properties = ["invertible"] }
SWAP = { properties = ["controllable", "invertible"] }
CZ = { properties = ["invertible"] }

# Supported qumode gates
Fourier = { properties = ["controllable", "invertible"] }
Displacement = { properties = ["controllable", "invertible", "differentiable"] }
Squeezing = { properties = ["controllable", "invertible", "differentiable"] }
Rotation = { properties = ["controllable", "invertible", "differentiable"] }
Kerr = { properties = ["invertible", "differentiable"] }
CubicPhase = { properties = ["invertible", "differentiable"] }
Beamsplitter = { properties = ["controllable", "invertible", "differentiable"] }
TwoModeSqueezing = { properties = ["controllable", "invertible", "differentiable"] }
TwoModeSum = { properties = ["controllable", "invertible", "differentiable"] }
ModeSwap = { properties = ["controllable", "invertible"] }
SelectiveNumberArbitraryPhase = { properties = ["invertible", "differentiable"] }

# Supported hybrid gates
ConditionalParity = { properties = ["invertible"] }
ConditionalDisplacement = { properties = ["invertible", "differentiable"] }
ConditionalSqueezing = { properties = ["invertible", "differentiable"] }
ConditionalRotation = { properties = ["invertible", "differentiable"] }
JaynesCummings = { properties = ["invertible", "differentiable"] }
AntiJaynesCummings = { properties = ["invertible", "differentiable"] }
SelectiveQubitRotation = { properties = ["invertible", "differentiable"] }
ConditionalTwoModeSqueezing = { properties = ["invertible", "differentiable"] }
ConditionalTwoModeSum = { properties = ["invertible", "differentiable"] }
ConditionalBeamsplitter = { properties = ["invertible", "differentiable"] }

[operators.observables]

PauliX = { }
PauliY = { }
PauliZ = { }
Hamiltonian = { conditions = ["terms-commute"] }
Sum = { conditions = ["terms-commute"] }
SProd = {}
Prod = {}

Position = { }
Momentum = { }
NumberOperator = { }
