# Workflow to release the package to PyPI whenever a "release" is marked
# on the protected branches (under the `pypi` environment).
# .github/workflows/release.yml
name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6

      - name: Build package
        run: uv build

      # Uses trusted publishing; no token needed.
      # see https://github.com/astral-sh/trusted-publishing-examples/blob/main/.github/workflows/release.yml
      - name: Publish to PyPI
        run: uv publish --trusted-publishing always